import "../blocks/header/header.js";
import "../blocks/home/home.js";
import "../blocks/d-down/d-down.js";
import "../blocks/p-slider/p-slider.js";
import "../blocks/p-video/p-video.js";
import "../blocks/tab/tab.js";
import "../blocks/i-hard/i-hard.js";
import "../blocks/modal/modal.js";
import "../blocks/m-explore/m-explore.js";